@startuml
actor       用户       as 用户
用户 -> 互动小程序任务列表 : 点击前往关注\n蓝月亮公众号
互动小程序任务列表 -> 互动后台 : 小程序发送unionid以及目标公众号\n的appid查询是否有关注公众号
互动后台 -> 微灵后台 : 如果互动后台没有数据，\n则把unionid以及目标公众号\nappid发到微灵后台
互动后台 -> 互动小程序任务列表 : 如果有数据直接从互动后台返回
微灵后台 -> 微灵后台 : 根据unionid以及公众号\nappid查询数据库是否有关注
微灵后台 -> 互动后台 : 返回查询结果
互动后台 -> 互动小程序任务列表 : 返回数据
@enduml